Comment out sections in rust.yml workflow

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -1,142 +1,142 @@
----
-name: Rust
+# ---
+# name: Rust
 
-'on':
-  push:
-    paths:
-      - .github/workflows/rust.yml
-      - '**/Cargo.*'
-      - c/include/**
-      - rust/*.toml
-      - rust/crates/**
-      - rust/examples/**
-      - rust/src/**
-  pull_request:
-    paths:
-      - .github/workflows/rust.yml
-      - '**/Cargo.*'
-      - c/include/**
-      - rust/*.toml
-      - rust/crates/**
-      - rust/examples/**
-      - rust/src/**
+# 'on':
+#   push:
+#     paths:
+#       - .github/workflows/rust.yml
+#       - '**/Cargo.*'
+#       - c/include/**
+#       - rust/*.toml
+#       - rust/crates/**
+#       - rust/examples/**
+#       - rust/src/**
+#   pull_request:
+#     paths:
+#       - .github/workflows/rust.yml
+#       - '**/Cargo.*'
+#       - c/include/**
+#       - rust/*.toml
+#       - rust/crates/**
+#       - rust/examples/**
+#       - rust/src/**
 
-permissions:
-  contents: read
+# permissions:
+#   contents: read
 
-concurrency:
-  group: ${{ github.ref }}-rust
-  cancel-in-progress: true
+# concurrency:
+#   group: ${{ github.ref }}-rust
+#   cancel-in-progress: true
 
-defaults:
-  run:
-    working-directory: rust
+# defaults:
+#   run:
+#     working-directory: rust
 
-env:
-  CARGO_CACHE_PATH: |
-    ~/.cargo/bin/
-    ~/.cargo/registry/index/
-    ~/.cargo/registry/cache/
-    ~/.cargo/git/db/
-    target/
+# env:
+#   CARGO_CACHE_PATH: |
+#     ~/.cargo/bin/
+#     ~/.cargo/registry/index/
+#     ~/.cargo/registry/cache/
+#     ~/.cargo/git/db/
+#     target/
 
-jobs:
-  msrv:
-    name: Minimum supported Rust version
-    runs-on: ${{ matrix.runner }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - runner: ubuntu-latest
-            rv: 1.77.0
-          - runner: windows-latest
-            rv: 1.82.0
-          - runner: macos-latest
-            rv: 1.77.0
-    steps:
-      - uses: actions/checkout@v7
-      - uses: actions/cache@v6
-        with:
-          path: ${{ env.CARGO_CACHE_PATH }}
-          key: "\
-            ${{ runner.os }}-cargo-\
-            ${{ hashFiles('**/Cargo.lock') }}"
-          restore-keys: "\
-            ${{ runner.os }}-cargo-"
-      - run: rustup install ${{ matrix.rv }}
-      - run: >
-          cargo +${{ matrix.rv }} check --workspace --all-targets --all-features
+# jobs:
+#   msrv:
+#     name: Minimum supported Rust version
+#     runs-on: ${{ matrix.runner }}
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         include:
+#           - runner: ubuntu-latest
+#             rv: 1.77.0
+#           - runner: windows-latest
+#             rv: 1.82.0
+#           - runner: macos-latest
+#             rv: 1.77.0
+#     steps:
+#       - uses: actions/checkout@v7
+#       - uses: actions/cache@v6
+#         with:
+#           path: ${{ env.CARGO_CACHE_PATH }}
+#           key: "\
+#             ${{ runner.os }}-cargo-\
+#             ${{ hashFiles('**/Cargo.lock') }}"
+#           restore-keys: "\
+#             ${{ runner.os }}-cargo-"
+#       - run: rustup install ${{ matrix.rv }}
+#       - run: >
+#           cargo +${{ matrix.rv }} check --workspace --all-targets --all-features
 
-  deny:
-    name: Deny
-    runs-on: ${{ matrix.runner }}
-    strategy:
-      fail-fast: false
-      matrix:
-        runner: [ubuntu-latest, windows-latest, macos-latest]
-    steps:
-      - uses: actions/checkout@v7
-      - uses: actions/cache@v6
-        with:
-          path: ${{ env.CARGO_CACHE_PATH }}
-          key: "\
-            ${{ runner.os }}-cargo-deny-\
-            ${{ hashFiles('**/Cargo.lock') }}"
-          restore-keys: "\
-            ${{ runner.os }}-cargo-deny-"
-      - run: cargo install --locked cargo-deny || true
-      - run: cargo deny --workspace --all-features check --show-stats
+#   deny:
+#     name: Deny
+#     runs-on: ${{ matrix.runner }}
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         runner: [ubuntu-latest, windows-latest, macos-latest]
+#     steps:
+#       - uses: actions/checkout@v7
+#       - uses: actions/cache@v6
+#         with:
+#           path: ${{ env.CARGO_CACHE_PATH }}
+#           key: "\
+#             ${{ runner.os }}-cargo-deny-\
+#             ${{ hashFiles('**/Cargo.lock') }}"
+#           restore-keys: "\
+#             ${{ runner.os }}-cargo-deny-"
+#       - run: cargo install --locked cargo-deny || true
+#       - run: cargo deny --workspace --all-features check --show-stats
 
-  rustfmt:
-    name: Rustfmt
-    runs-on: ${{ matrix.runner }}
-    strategy:
-      fail-fast: false
-      matrix:
-        runner: [ubuntu-latest, windows-latest, macos-latest]
-    steps:
-      - uses: actions/checkout@v7
-      - run: cargo fmt --all -- --check
+#   rustfmt:
+#     name: Rustfmt
+#     runs-on: ${{ matrix.runner }}
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         runner: [ubuntu-latest, windows-latest, macos-latest]
+#     steps:
+#       - uses: actions/checkout@v7
+#       - run: cargo fmt --all -- --check
 
-  check:
-    name: Check
-    runs-on: ${{ matrix.runner }}
-    strategy:
-      fail-fast: false
-      matrix:
-        runner: [ubuntu-latest, windows-latest, macos-latest]
-        include:
-          - name: all-features
-            f: --all-features
-          - name: alloc
-            f: --no-default-features --features alloc
-          - name: core
-            f: --no-default-features
-    steps:
-      - uses: actions/checkout@v7
-      - uses: actions/cache@v6
-        with:
-          path: ${{ env.CARGO_CACHE_PATH }}
-          key: "\
-            ${{ runner.os }}-cargo-check-\
-            ${{ matrix.name }}-${{ hashFiles('**/Cargo.lock') }}"
-          restore-keys: "\
-            ${{ runner.os }}-cargo-check-\
-            ${{ matrix.name }}-"
-      - name: Check
-        run: cargo check --workspace --all-targets ${{ matrix.f }}
-      - name: Clippy
-        run: >
-          cargo clippy --workspace --all-targets ${{ matrix.f }} -- -Dwarnings
-      - name: Test
-        run: cargo test --workspace --all-targets ${{ matrix.f }}
-      - name: Doctest
-        run: cargo test --workspace --doc ${{ matrix.f }}
-      - name: Install `no_std` target
-        run: rustup target add thumbv7em-none-eabi
-        if: matrix.name != 'all-features'
-      - name: Check `no_std` target
-        if: matrix.name != 'all-features'
-        run: >
-          cargo check --workspace --target thumbv7em-none-eabi ${{ matrix.f }}
+#   check:
+#     name: Check
+#     runs-on: ${{ matrix.runner }}
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         runner: [ubuntu-latest, windows-latest, macos-latest]
+#         include:
+#           - name: all-features
+#             f: --all-features
+#           - name: alloc
+#             f: --no-default-features --features alloc
+#           - name: core
+#             f: --no-default-features
+#     steps:
+#       - uses: actions/checkout@v7
+#       - uses: actions/cache@v6
+#         with:
+#           path: ${{ env.CARGO_CACHE_PATH }}
+#           key: "\
+#             ${{ runner.os }}-cargo-check-\
+#             ${{ matrix.name }}-${{ hashFiles('**/Cargo.lock') }}"
+#           restore-keys: "\
+#             ${{ runner.os }}-cargo-check-\
+#             ${{ matrix.name }}-"
+#       - name: Check
+#         run: cargo check --workspace --all-targets ${{ matrix.f }}
+#       - name: Clippy
+#         run: >
+#           cargo clippy --workspace --all-targets ${{ matrix.f }} -- -Dwarnings
+#       - name: Test
+#         run: cargo test --workspace --all-targets ${{ matrix.f }}
+#       - name: Doctest
+#         run: cargo test --workspace --doc ${{ matrix.f }}
+#       - name: Install `no_std` target
+#         run: rustup target add thumbv7em-none-eabi
+#         if: matrix.name != 'all-features'
+#       - name: Check `no_std` target
+#         if: matrix.name != 'all-features'
+#         run: >
+#           cargo check --workspace --target thumbv7em-none-eabi ${{ matrix.f }}
